server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /config.js {
        add_header Cache-Control "no-store";
    }

    location ~* \.(?:apk|exe)$ {
        add_header Content-Disposition "attachment";
        add_header Cache-Control "public, max-age=3600";
        try_files $uri =404;
    }
}
